### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by dadaniyalamjad** [Ralfarios/antd-input-otp#10]
When I come to the OTP screen, I'm not getting auto-focus on the first box for entering the OTP.

![image](https://github.com/Ralfarios/antd-input-otp/assets/45781695/a34b1192-07f9-4076-9c49-5223dbc3c455)

**Comment by Ralfarios** [comment]
I will check it and work on it in the next update, thank you for your report..

Cheers,
R.

**Comment by Ralfarios** [comment]
@dadaniyalamjad Hello, checkout the latest version (v1.1.0), we have autofocus and inputref, also you can paste your otp too, and make sure the value type and input type are the same.

Cheers, 
R.
