### ISSUE TITLE
Changing input style after filling

### ISSUE THREAD

**Issue by mohammadbrzbrz72** [Ralfarios/antd-input-otp#15]
How can I change the style of inputs after they have been filled?

for example change the background or border style.

![antd-otp](https://github.com/Ralfarios/antd-input-otp/assets/46639490/2964e460-8a45-45da-86a6-a03949401cda)

**Comment by Ralfarios** [comment]
Hello, @mohammadbrzbrz72 

May I know which antd ver. are you currently using in your project?

Cheers,
R.

**Comment by mohammadbrzbrz72** [comment]
In my project the antd version is "^5.6.1", 
And the antd-input-otp is "^1.1.0"

**Comment by mohammadbrzbrz72** [comment]
Would you please tell me how can I do that?

**Comment by Ralfarios** [comment]
First thing first, you need to add `inputClassName` to your component, let's say it's 
```tsx
<InputOTP
  // Other props...
  inputClassName="input_otp"
/>
```

and then on your CSS files, use this className with value as attribute selector..
```css
.input_otp[value]:not([value=""]){
  // Your desire style
}
```

It should work like a charm
![image](https://github.com/Ralfarios/antd-input-otp/assets/71214308/36a51749-949c-4ad0-a236-b3d273077689)

**Comment by mohammadbrzbrz72** [comment]
@Ralfarios 

Thank you very much for answering 🙏🙌❤️
