### ISSUE TITLE
WARNING in ./node_modules/antd-input-otp/dist/esm/index.es.js

### ISSUE THREAD

**Issue by dadaniyalamjad** [Ralfarios/antd-input-otp#3]
WARNING in ./node_modules/antd-input-otp/dist/esm/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\project\sportscom\node_modules\antd-input-otp\src\lib\InputOTP.component.tsx' file: Error: ENOENT: no such file or directory, open 'D:\project\sportscom\node_modules\antd-input-otp\src\lib\InputOTP.component.tsx'

WARNING in ./node_modules/antd-input-otp/dist/esm/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\project\sportscom\node_modules\antd-input-otp\src\lib\InputOTP.constants.ts' file: Error: ENOENT: no such file or directory, open 'D:\project\sportscom\node_modules\antd-input-otp\src\lib\InputOTP.constants.ts'

WARNING in ./node_modules/antd-input-otp/dist/esm/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\project\sportscom\node_modules\antd-input-otp\src\lib\InputOTP.hooks.ts' file: Error: ENOENT: no such file or directory, open 'D:\project\sportscom\node_modules\antd-input-otp\src\lib\InputOTP.hooks.ts'

i am using typescript

in javascipt these error not showing

**Comment by Ralfarios** [comment]
Hello, may I know which version of typescript, react and antd are you using right now?

Thank you,
R.

**Comment by dadaniyalamjad** [comment]
"antd": "^5.5.0",
 "antd-input-otp": "^1.0.1",
"react": "^18.2.0",
"typescript": "^4.9.5",

its running fine but these warning shows 
how to remove this warnings?

**Comment by Ralfarios** [comment]
I will do something about it on 1.0.2 ASAP.. Thank you for your report! 

Cheers, 🍻 
R.

**Comment by Ralfarios** [comment]
V1.0.2 is live now, please check it..

Thank you,
R.

**Comment by dadaniyalamjad** [comment]
these warning still show :(

**Comment by Ralfarios** [comment]
Can you provide me the codesandbox or anything for reproduce the bug?

Cheers, 
R.

**Comment by peter-sherif** [comment]
Using:
"antd": "^5.9.2",
"antd-input-otp": "^1.1.1",
"react": "^18.2.0",
"typescript": "^4.9.5",

The warnings are still showing.
Is there any solution to solve the warnings? Thanks!

**Comment by Ralfarios** [comment]
Let me check on the bundler.. hopefully I can fix this ASAP..

**Comment by Ralfarios** [comment]
Hello, @peter-sherif 

I guess you are using CRA or Webpack as a module bundler since the error isn't there when I use Vite.

I'm still working this out and can't give you an ETA. However, I can give you a workaround for this. Add this line of code to your `.env` file.
```
GENERATE_SOURCEMAP=false
```

Cheers,
R.
